import React, { useState, useEffect, useMemo } from "react";
import { Plus, Paperclip, X, CheckCircle2, Filter } from "lucide-react";
import { styles, THEME } from "../shared.js";
import { JalaliDateInput, toJalaliSafe } from "../personnel/jalaliDate.jsx";
import { fileToBase64 } from "../personnel/fileHelpers.js";
import {
  loadCorrectiveActions, createCorrectiveAction, updateCorrectiveAction, approveCorrectiveAction,
  uploadCorrectiveActionFile, loadContractorsForDropdown, computeKpis, isOverdue,
  SOURCE_OPTIONS, PRIORITY_OPTIONS, STATUS_META, STATUS_ORDER,
} from "./correctiveActionsApi.js";
import {
  loadTripodCorrectiveActionsForCompany, assignTripodCorrectiveActionContractor,
  updateTripodCorrectiveActionStatus, CA_STATUS_LABELS,
} from "../tripodBeta/tripodAnalysesApi.js";
import { useLanguage } from "../i18n/LanguageContext.jsx";

// نگاشت وضعیت‌های Tripod Beta (OPEN/IN_PROGRESS/DONE/CANCELLED) به واژگان
// همین لیست، فقط برای نمایش یکدست بج وضعیت — چیزی در دیتابیس تغییر نمی‌کند
const TRIPOD_STATUS_TO_META = { OPEN: "open", IN_PROGRESS: "in_progress", DONE: "done_pending_approval", CANCELLED: "expired" };

// اقدامات اصلاحیِ صادرشده در ماژول مدیریت حوادث/Tripod Beta در جدول
// جداگانه‌ی tripod_corrective_actions ذخیره می‌شوند (شرح/علت ریشه‌ای فقط
// از همان ماژول قابل‌ویرایش است) — اینجا برای «هم‌دیده‌شدن» در همین لیست،
// به همان شکل ردیف‌های corrective_actions نگاشت می‌شوند و با __tripodOrigin
// علامت‌گذاری می‌شوند تا با کلیک، به‌جای فرم عمومی، مودال «ارجاع به
// پیمانکار» باز شود (وضعیت خام Tripod هم در __tripodRawStatus نگه داشته
// می‌شود چون واژگان status نگاشت‌شده برای PATCH مناسب نیست).
function tripodActionToListItem(t) {
  return {
    id: t.id,
    actionNumber: `INC-${t.incidentNo || t.id.slice(-6).toUpperCase()}`,
    source: "incident",
    nonconformanceDescription: [t.titleFa, t.description].filter(Boolean).join(" — ") || "—",
    responsibleContractorId: t.responsibleContractorId || "",
    responsibleContractorName: t.responsibleContractorName || "",
    responsiblePerson: t.responsiblePerson,
    projectName: t.incidentLocation || "",
    dueDate: t.dueDate,
    priority: "medium",
    status: TRIPOD_STATUS_TO_META[t.status] || "open",
    completedAt: "",
    approvedAt: "",
    approvedBy: "",
    attachments: [],
    createdAt: t.createdAt,
    autoGenerated: false,
    __tripodOrigin: true,
    __tripodRawStatus: t.status || "OPEN",
  };
}

const EMPTY_FORM = {
  actionNumber: "", source: "other", nonconformanceDescription: "", rootCause: "", actionDescription: "",
  responsibleContractorId: "", responsibleContractorName: "", responsiblePerson: "", projectName: "",
  dueDate: "", priority: "medium", status: "open", completedAt: "", executorNotes: "", attachments: [],
  approvedBy: "", approvedAt: "", approverNotes: "",
};

const EMPTY_FILTERS = { contractorId: "", projectName: "", responsiblePerson: "", status: "", priority: "", search: "" };

export default function CorrectiveActionsDashboard({ onBack, currentUser }) {
  const { t, dir } = useLanguage();
  const [list, setList] = useState([]);
  const [contractors, setContractors] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(EMPTY_FORM);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [filters, setFilters] = useState(EMPTY_FILTERS);
  const [showFilters, setShowFilters] = useState(false);
  const [kpiFilter, setKpiFilter] = useState(""); // کلیک روی یک کارت KPI، لیست را فیلتر می‌کند
  const [assignTripodAction, setAssignTripodAction] = useState(null); // اقدام Tripod Beta در حال ارجاع به پیمانکار

  const isContractor = currentUser?.role === "CONTRACTOR";

  const load = async () => {
    const [rows, contractorRows, tripodRows] = await Promise.all([
      loadCorrectiveActions(), loadContractorsForDropdown(), loadTripodCorrectiveActionsForCompany(),
    ]);
    const merged = [...rows, ...tripodRows.map(tripodActionToListItem)]
      .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0));
    setList(merged);
    setContractors(contractorRows);
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const kpis = useMemo(() => computeKpis(list), [list]);

  const filtered = useMemo(() => {
    const explicitlyWantsClosed = kpiFilter === "closed" || filters.status === "closed";
    return list.filter((a) => {
      // طبق خواسته‌ی صریح: در لیست پیش‌فرض، اقدامات «بسته‌شده» نمایش داده
      // نشوند — مگر اینکه کاربر خودش صریحاً بخواهد ببیندشان
      if (!explicitlyWantsClosed && a.status === "closed") return false;
      if (kpiFilter === "overdue" && !isOverdue(a)) return false;
      if (kpiFilter && kpiFilter !== "overdue" && a.status !== kpiFilter) return false;
      if (filters.contractorId && a.responsibleContractorId !== filters.contractorId) return false;
      if (filters.projectName && !a.projectName.toLowerCase().includes(filters.projectName.toLowerCase())) return false;
      if (filters.responsiblePerson && !a.responsiblePerson.toLowerCase().includes(filters.responsiblePerson.toLowerCase())) return false;
      if (filters.status && a.status !== filters.status) return false;
      if (filters.priority && a.priority !== filters.priority) return false;
      if (filters.search && !(`${a.actionNumber} ${a.nonconformanceDescription}`.toLowerCase().includes(filters.search.toLowerCase()))) return false;
      return true;
    });
  }, [list, filters, kpiFilter]);

  const openNew = () => { setForm(EMPTY_FORM); setEditingId(null); setError(""); setShowForm(true); };
  const openEdit = (a) => {
    setForm({
      actionNumber: a.actionNumber, source: a.source, nonconformanceDescription: a.nonconformanceDescription,
      rootCause: a.rootCause, actionDescription: a.actionDescription, responsibleContractorId: a.responsibleContractorId,
      responsibleContractorName: a.responsibleContractorName, responsiblePerson: a.responsiblePerson, projectName: a.projectName,
      dueDate: a.dueDate, priority: a.priority, status: a.status, completedAt: a.completedAt, executorNotes: a.executorNotes,
      attachments: a.attachments, approvedBy: a.approvedBy, approvedAt: a.approvedAt, approverNotes: a.approverNotes,
    });
    setEditingId(a.id);
    setError("");
    setShowForm(true);
  };

  const handleSave = async () => {
    if (!form.nonconformanceDescription.trim()) { setError(t("errNonconformanceDescRequired")); return; }
    setSaving(true);
    setError("");
    const result = editingId
      ? await updateCorrectiveAction(editingId, form)
      : await createCorrectiveAction(form, currentUser?.name);
    setSaving(false);
    if (result?.__error) { setError(result.message); return; }
    setShowForm(false);
    await load();
  };

  const handleApprove = async () => {
    if (!editingId) return;
    setSaving(true);
    // اول تغییرات فعلی فرم ذخیره شود، بعد وضعیت به «بسته‌شده» تغییر کند
    const saveResult = await updateCorrectiveAction(editingId, form);
    if (saveResult?.__error) { setSaving(false); setError(saveResult.message); return; }
    const result = await approveCorrectiveAction(editingId, currentUser?.name, form.approverNotes);
    setSaving(false);
    if (result?.__error) { setError(result.message); return; }
    setShowForm(false);
    await load();
  };

  const handleFileUpload = async (file) => {
    if (!file) return;
    setUploading(true);
    try {
      const base64 = await fileToBase64(file);
      const result = await uploadCorrectiveActionFile(base64, file.name, file.type);
      setUploading(false);
      if (result?.__error) { setError(result.message); return; }
      setForm((prev) => ({ ...prev, attachments: [...prev.attachments, result] }));
    } catch (e) {
      setUploading(false);
      setError(e?.message || t("errCaUploadFile"));
    }
  };

  const removeAttachment = (idx) => {
    setForm((prev) => ({ ...prev, attachments: prev.attachments.filter((_, i) => i !== idx) }));
  };

  if (loading) return <div style={{ padding: 24, textAlign: "center", color: THEME.text3 }}>{t("commonLoading")}</div>;

  // ---------- فرم ثبت/ویرایش ----------
  if (showForm) {
    return (
      <div style={{ maxWidth: 640, margin: "0 auto", padding: 24, direction: dir }}>
        <div style={styles.backLink} onClick={() => setShowForm(false)}>{t("cadCancel")}</div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }}>
          <h2 style={{ fontSize: 17, color: THEME.navy, fontWeight: 700, margin: 0 }}>{editingId ? t("cadEditTitle") : t("cadNewTitle")}</h2>
          {editingId && <StatusBadge status={form.status} />}
        </div>

        <div style={{ ...styles.card, width: "auto", marginBottom: 14 }}>
          <h3 style={{ fontSize: 13, color: THEME.navy, margin: "0 0 10px", fontWeight: 700 }}>{t("cadMainInfo")}</h3>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadActionNumber")}</label>
              <input style={styles.input} value={form.actionNumber} onChange={(e) => setForm({ ...form, actionNumber: e.target.value })} dir="ltr" placeholder={t("cadAutoIfEmpty")} />
            </div>
            <div>
              <label style={styles.label}>{t("cadSourceLabel")}</label>
              <select style={styles.input} value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} dir={dir}>
                {SOURCE_OPTIONS.map((s) => <option key={s.value} value={s.value}>{s.labelKey ? t(s.labelKey) : s.label}</option>)}
              </select>
            </div>
          </div>

          <label style={styles.label}>{t("cadNonconformanceDesc")}</label>
          <textarea style={{ ...styles.input, minHeight: 60, fontFamily: "inherit" }} value={form.nonconformanceDescription} onChange={(e) => setForm({ ...form, nonconformanceDescription: e.target.value })} dir={dir} />

          <label style={styles.label}>{t("cadRootCause")}</label>
          <textarea style={{ ...styles.input, minHeight: 50, fontFamily: "inherit" }} value={form.rootCause} onChange={(e) => setForm({ ...form, rootCause: e.target.value })} dir={dir} />

          <label style={styles.label}>{t("cadActionDesc")}</label>
          <textarea style={{ ...styles.input, minHeight: 60, fontFamily: "inherit" }} value={form.actionDescription} onChange={(e) => setForm({ ...form, actionDescription: e.target.value })} dir={dir} />
        </div>

        <div style={{ ...styles.card, width: "auto", marginBottom: 14 }}>
          <h3 style={{ fontSize: 13, color: THEME.navy, margin: "0 0 10px", fontWeight: 700 }}>{t("cadResponsibilityTiming")}</h3>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadResponsibleContractor")}</label>
              <select
                style={styles.input}
                value={form.responsibleContractorId}
                onChange={(e) => {
                  const c = contractors.find((x) => x.id === e.target.value);
                  setForm({ ...form, responsibleContractorId: e.target.value, responsibleContractorName: c?.name || "" });
                }}
                dir={dir}
              >
                <option value="">{t("fieldSelectPlaceholder")}</option>
                {contractors.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            <div>
              <label style={styles.label}>{t("cadResponsibleExecutorName")}</label>
              <input style={styles.input} value={form.responsiblePerson} onChange={(e) => setForm({ ...form, responsiblePerson: e.target.value })} dir={dir} />
            </div>
          </div>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadProject")}</label>
              <input style={styles.input} value={form.projectName} onChange={(e) => setForm({ ...form, projectName: e.target.value })} dir={dir} />
            </div>
            <div>
              <label style={styles.label}>{t("cadPriority")}</label>
              <select style={styles.input} value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} dir={dir}>
                {PRIORITY_OPTIONS.map((p) => <option key={p.value} value={p.value}>{t(p.labelKey)}</option>)}
              </select>
            </div>
          </div>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadDueDate")}</label>
              <JalaliDateInput value={form.dueDate} onChange={(v) => setForm({ ...form, dueDate: v })} allowEmpty />
            </div>
            <div>
              <label style={styles.label}>{t("cadActionStatus")}</label>
              <select style={styles.input} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} dir={dir}>
                {STATUS_ORDER.map((s) => <option key={s} value={s}>{STATUS_META[s].emoji} {t(STATUS_META[s].labelKey)}</option>)}
              </select>
            </div>
          </div>
        </div>

        <div style={{ ...styles.card, width: "auto", marginBottom: 14 }}>
          <h3 style={{ fontSize: 13, color: THEME.navy, margin: "0 0 10px", fontWeight: 700 }}>{t("cadExecutionDocumentation")}</h3>
          <label style={styles.label}>{t("cadCompletionDate")}</label>
          <JalaliDateInput value={form.completedAt} onChange={(v) => setForm({ ...form, completedAt: v })} allowEmpty />
          <label style={styles.label}>{t("cadExecutorNotes")}</label>
          <textarea style={{ ...styles.input, minHeight: 50, fontFamily: "inherit" }} value={form.executorNotes} onChange={(e) => setForm({ ...form, executorNotes: e.target.value })} dir={dir} />

          <label style={styles.label}>{t("cadDocsAndPhotos")}</label>
          {form.attachments.length > 0 && (
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 10 }}>
              {form.attachments.map((att, i) => (
                <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, background: "#f1f3f5", borderRadius: 8, padding: "6px 10px" }}>
                  <a href={att.url} target="_blank" rel="noreferrer" style={{ fontSize: 11, color: THEME.tealDeep, textDecoration: "none" }}>{att.name}</a>
                  <button type="button" onClick={() => removeAttachment(i)} style={{ background: "none", border: "none", cursor: "pointer", color: THEME.text3 }}><X size={12} /></button>
                </div>
              ))}
            </div>
          )}
          <label style={{ ...styles.smallButton, display: "inline-flex", alignItems: "center", gap: 6, background: THEME.navyMid, cursor: "pointer" }}>
            <Paperclip size={13} /> {uploading ? t("cadUploading") : t("cadAddFile")}
            <input type="file" accept="image/*,.pdf" style={{ display: "none" }} onChange={(e) => { handleFileUpload(e.target.files?.[0]); e.target.value = ""; }} disabled={uploading} />
          </label>
        </div>

        {!isContractor && (
          <div style={{ ...styles.card, width: "auto", marginBottom: 14 }}>
            <h3 style={{ fontSize: 13, color: THEME.navy, margin: "0 0 10px", fontWeight: 700 }}>{t("cadHseApproval")}</h3>
            {form.approvedBy
              ? <p style={{ fontSize: 11.5, color: THEME.text2 }}>{t("cadApprovedByOn", { name: form.approvedBy, date: toJalaliSafe(form.approvedAt) })}</p>
              : <p style={{ fontSize: 11.5, color: THEME.text3 }}>{t("cadNotApprovedYet")}</p>}
            <label style={styles.label}>{t("cadApproverNotes")}</label>
            <textarea style={{ ...styles.input, minHeight: 50, fontFamily: "inherit" }} value={form.approverNotes} onChange={(e) => setForm({ ...form, approverNotes: e.target.value })} dir={dir} />
          </div>
        )}

        {error && <p style={styles.error}>{error}</p>}
        <div style={{ display: "flex", gap: 8 }}>
          <button type="button" style={styles.button} onClick={handleSave} disabled={saving}>{saving ? t("saSavingEllipsis") : t("commonSave")}</button>
          {!isContractor && editingId && form.status !== "closed" && (
            <button type="button" style={{ ...styles.button, background: "#166534", display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }} onClick={handleApprove} disabled={saving}>
              <CheckCircle2 size={15} /> {t("cadApproveAndClose")}
            </button>
          )}
        </div>
      </div>
    );
  }

  // ---------- لیست + داشبورد ----------
  return (
    <div style={{ maxWidth: 1000, margin: "0 auto", padding: 24, direction: dir }}>
      {onBack && <div style={styles.backLink} onClick={onBack}>{t("commonBack")}</div>}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 14, flexWrap: "wrap" }}>
        <h2 style={{ margin: 0, fontSize: 19, color: THEME.navy, fontWeight: 700 }}>{t("cadListTitle")}</h2>
        <button type="button" style={{ ...styles.smallButton, display: "flex", alignItems: "center", gap: 6 }} onClick={openNew}>
          <Plus size={13} /> {t("cadNewAction")}
        </button>
      </div>

      {/* کارت‌های آماری KPI */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: 8, marginBottom: 16 }}>
        <KpiCard label={t("cadKpiTotal")} value={kpis.total} active={kpiFilter === ""} onClick={() => setKpiFilter("")} color={THEME.navy} />
        <KpiCard label={t("statusOpen")} value={kpis.open} active={kpiFilter === "open"} onClick={() => setKpiFilter("open")} color={STATUS_META.open.bg} />
        <KpiCard label={t("caStatusInProgress")} value={kpis.in_progress} active={kpiFilter === "in_progress"} onClick={() => setKpiFilter("in_progress")} color={STATUS_META.in_progress.bg} />
        <KpiCard label={t("cadKpiPendingApproval")} value={kpis.done_pending_approval} active={kpiFilter === "done_pending_approval"} onClick={() => setKpiFilter("done_pending_approval")} color="#b45309" />
        <KpiCard label={t("statusClosed")} value={kpis.closed} active={kpiFilter === "closed"} onClick={() => setKpiFilter("closed")} color={STATUS_META.closed.bg} />
        <KpiCard label={t("caStatusExpired")} value={kpis.expired} active={kpiFilter === "expired"} onClick={() => setKpiFilter("expired")} color={STATUS_META.expired.bg} />
        <KpiCard label={t("cadKpiOverdue")} value={kpis.overdue} active={kpiFilter === "overdue"} onClick={() => setKpiFilter("overdue")} color="#7c2d12" />
      </div>

      {/* فیلترها */}
      <button type="button" onClick={() => setShowFilters((v) => !v)} style={{ ...styles.smallButton, background: THEME.navyMid, display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
        <Filter size={13} /> {t("pmdFilters")}
      </button>
      {showFilters && (
        <div style={{ ...styles.card, width: "auto", marginBottom: 14 }}>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("fieldContractor")}</label>
              <select style={styles.input} value={filters.contractorId} onChange={(e) => setFilters({ ...filters, contractorId: e.target.value })} dir={dir}>
                <option value="">{t("cadEveryone")}</option>
                {contractors.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            <div>
              <label style={styles.label}>{t("cadProject")}</label>
              <input style={styles.input} value={filters.projectName} onChange={(e) => setFilters({ ...filters, projectName: e.target.value })} dir={dir} />
            </div>
          </div>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadResponsiblePersonLabel")}</label>
              <input style={styles.input} value={filters.responsiblePerson} onChange={(e) => setFilters({ ...filters, responsiblePerson: e.target.value })} dir={dir} />
            </div>
            <div>
              <label style={styles.label}>{t("cadStatusLabel")}</label>
              <select style={styles.input} value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} dir={dir}>
                <option value="">{t("cadEveryone")}</option>
                {STATUS_ORDER.map((s) => <option key={s} value={s}>{STATUS_META[s].emoji} {t(STATUS_META[s].labelKey)}</option>)}
              </select>
            </div>
          </div>
          <div style={styles.formGrid}>
            <div>
              <label style={styles.label}>{t("cadPriority")}</label>
              <select style={styles.input} value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value })} dir={dir}>
                <option value="">{t("cadEveryone")}</option>
                {PRIORITY_OPTIONS.map((p) => <option key={p.value} value={p.value}>{t(p.labelKey)}</option>)}
              </select>
            </div>
            <div>
              <label style={styles.label}>{t("cadSearchNumberDesc")}</label>
              <input style={styles.input} value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} dir={dir} />
            </div>
          </div>
          <button type="button" style={{ ...styles.smallButton, background: THEME.text3 }} onClick={() => setFilters(EMPTY_FILTERS)}>{t("cadClearFilters")}</button>
        </div>
      )}

      {filtered.length === 0 && <p style={{ color: THEME.text3, textAlign: "center", padding: "30px 0" }}>{t("cadNoItemsFound")}</p>}

      {filtered.map((a) => (
        <div
          key={a.id}
          style={{ ...styles.card, width: "auto", marginBottom: 8, cursor: "pointer" }}
          onClick={() => { if (a.__tripodOrigin) setAssignTripodAction(a); else openEdit(a); }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8, flexWrap: "wrap" }}>
            <div style={{ flex: 1, minWidth: 200 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
                <span style={{ fontWeight: 700, color: THEME.navy, fontSize: 13, direction: "ltr" }}>{a.actionNumber}</span>
                <StatusBadge status={a.status} />
                {isOverdue(a) && <span style={{ fontSize: 10, background: "#7c2d12", color: "#fff", padding: "2px 8px", borderRadius: 999 }}>{t("cadOverdueBadge")}</span>}
                {a.autoGenerated && <span style={{ fontSize: 10, background: THEME.tealSoft, color: THEME.tealDeep, padding: "2px 8px", borderRadius: 999 }}>{t("cadAutoBadge")}</span>}
                {a.__tripodOrigin && <span style={{ fontSize: 10, background: THEME.tealSoft, color: THEME.tealDeep, padding: "2px 8px", borderRadius: 999 }}>{t("cadTripodOriginBadge")}</span>}
              </div>
              <div style={{ fontSize: 12, color: THEME.text2, marginTop: 5 }}>{a.nonconformanceDescription.slice(0, 130)}{a.nonconformanceDescription.length > 130 ? "…" : ""}</div>
              <div style={{ fontSize: 10.5, color: THEME.text3, marginTop: 5 }}>
                {a.responsibleContractorName && <>{t("cadContractorInline", { name: a.responsibleContractorName })}</>}
                {a.responsiblePerson && <>{t("cadResponsibleInline", { name: a.responsiblePerson })}</>}
                {a.dueDate && <>{t("cadDueInline", { date: toJalaliSafe(a.dueDate) })}</>}
                {a.createdAt && <>{t("cadCreatedInline", { date: toJalaliSafe(a.createdAt) })}</>}
              </div>
              {a.__tripodOrigin ? (
                <div style={{ fontSize: 10.5, color: THEME.text3, marginTop: 3 }}>
                  {t("cadTripodOriginHint")}
                </div>
              ) : (
                <div style={{ fontSize: 10.5, color: THEME.text3, marginTop: 3 }}>
                  {a.completedAt && <>{t("cadExecutionDateInline", { date: toJalaliSafe(a.completedAt) })}</>}
                  {a.approvedAt
                    ? <>{t("cadEmployerApprovalInline", { date: toJalaliSafe(a.approvedAt) })}{a.approvedBy && ` (${a.approvedBy})`}</>
                    : <span style={{ color: "#b45309" }}>{t("cadNotApprovedByEmployerYet")}</span>}
                </div>
              )}
            </div>
          </div>
        </div>
      ))}

      {assignTripodAction && (
        <TripodActionAssignModal
          action={assignTripodAction}
          contractors={contractors}
          onClose={() => setAssignTripodAction(null)}
          onSaved={async () => { setAssignTripodAction(null); await load(); }}
        />
      )}
    </div>
  );
}

// ارجاع یک اقدام اصلاحیِ Tripod Beta به یک شرکت/پیمانکار مشخص جهت پیگیری،
// و در صورت نیاز به‌روزرسانی وضعیت پیگیری — مستقیماً روی همان رکورد
// tripod_corrective_actions (بدون ساخت رکورد موازی در corrective_actions،
// تا دو نسخه‌ی متفاوت از یک اقدام از هم واگرا نشوند)
function TripodActionAssignModal({ action, contractors, onClose, onSaved }) {
  const { t, dir } = useLanguage();
  const [contractorId, setContractorId] = useState(action.responsibleContractorId || "");
  const [status, setStatus] = useState(action.__tripodRawStatus || "OPEN");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const handleSave = async () => {
    setSaving(true);
    setError("");
    const contractor = contractors.find((c) => c.id === contractorId);
    const tasks = [assignTripodCorrectiveActionContractor(action.id, contractorId || null, contractor?.name || "")];
    if (status !== action.__tripodRawStatus) tasks.push(updateTripodCorrectiveActionStatus(action.id, status));
    const results = await Promise.all(tasks);
    setSaving(false);
    const failed = results.find((r) => r?.__error);
    if (failed) { setError(failed.message); return; }
    onSaved();
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(15,42,63,0.5)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: 16 }} onClick={onClose}>
      <div style={{ background: THEME.surface, borderRadius: 14, padding: 22, maxWidth: 440, width: "100%", maxHeight: "85vh", overflowY: "auto", direction: dir }} onClick={(e) => e.stopPropagation()}>
        <h3 style={{ fontSize: 15, color: THEME.navy, fontWeight: 800, margin: "0 0 12px" }}>{t("cadTripodAssignTitle")}</h3>
        <div style={{ background: THEME.bg, borderRadius: 8, padding: 10, marginBottom: 12, fontSize: 11.5, color: THEME.text2, lineHeight: 1.9 }}>
          {action.nonconformanceDescription}
        </div>

        <label style={styles.label}>{t("cadTripodAssignContractorLabel")}</label>
        <select style={styles.input} value={contractorId} onChange={(e) => setContractorId(e.target.value)} dir={dir}>
          <option value="">{t("cadTripodNoAssignment")}</option>
          {contractors.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>

        <label style={styles.label}>{t("cadTripodFollowUpStatus")}</label>
        <select style={styles.input} value={status} onChange={(e) => setStatus(e.target.value)} dir={dir}>
          {Object.entries(CA_STATUS_LABELS).map(([k, v]) => <option key={k} value={k}>{t(v)}</option>)}
        </select>

        <p style={{ fontSize: 10.5, color: THEME.text3, marginTop: 10 }}>
          {t("cadTripodEditNote")}
        </p>

        {error && <p style={styles.error}>{error}</p>}
        <div style={{ display: "flex", gap: 8, marginTop: 16 }}>
          <button type="button" style={styles.smallButton} onClick={handleSave} disabled={saving}>{saving ? t("saSavingEllipsis") : t("commonSave")}</button>
          <button type="button" style={{ ...styles.smallButton, background: THEME.text3 }} onClick={onClose}>{t("commonCancel")}</button>
        </div>
      </div>
    </div>
  );
}

function KpiCard({ label, value, color, active, onClick }) {
  return (
    <div
      onClick={onClick}
      style={{
        background: active ? color : THEME.surface, color: active ? "#fff" : THEME.text, border: `1.5px solid ${active ? color : THEME.border}`,
        borderRadius: 10, padding: "10px 8px", textAlign: "center", cursor: "pointer",
      }}
    >
      <div style={{ fontSize: 20, fontWeight: 800 }}>{value}</div>
      <div style={{ fontSize: 10, fontWeight: 600, marginTop: 2 }}>{label}</div>
    </div>
  );
}

function StatusBadge({ status }) {
  const { t } = useLanguage();
  const meta = STATUS_META[status] || STATUS_META.open;
  return (
    <span style={{ fontSize: 10.5, fontWeight: 700, background: meta.bg, color: meta.color, padding: "3px 9px", borderRadius: 999, whiteSpace: "nowrap" }}>
      {meta.emoji} {t(meta.labelKey)}
    </span>
  );
}
