-- ترجمهٔ انگلیسی‌ی دادهٔ مرجع Tripod Beta (۵۵ پیش‌شرط، ۱۴۰ اشکال پنهان،
-- ۱۱ گروه چک‌لیست، ۴ دستهٔ هدف). متن‌های فارسی دست‌نخورده‌اند؛ فقط ستون‌های
-- *_en اضافه و پر می‌شوند. در حالت انگلیسی، متن انگلیسی و در حالت
-- فارسی، متن فارسی نمایش داده می‌شود (وب و موبایل یکسان).

alter table if exists public.tripod_ref_checklist_group  add column if not exists title_en text not null default '';
alter table if exists public.tripod_ref_precondition      add column if not exists text_en  text not null default '';
alter table if exists public.tripod_ref_hidden_failure    add column if not exists text_en  text not null default '';
alter table if exists public.tripod_ref_target_category   add column if not exists title_en text not null default '';
alter table if exists public.tripod_ref_target_category   add column if not exists potential_damage_en text not null default '';

update public.tripod_ref_checklist_group set title_en = 'Facilities, equipment and tools — layout (design, ergonomics, arrangement)' where group_no = 1;
update public.tripod_ref_checklist_group set title_en = 'Facilities, equipment and tools (condition, suitability, availability)' where group_no = 2;
update public.tripod_ref_checklist_group set title_en = 'Procedures, structure and work permits' where group_no = 3;
update public.tripod_ref_checklist_group set title_en = 'Adverse imposed conditions' where group_no = 4;
update public.tripod_ref_checklist_group set title_en = 'Work environment / housekeeping' where group_no = 5;
update public.tripod_ref_checklist_group set title_en = 'Awareness, training and competence' where group_no = 6;
update public.tripod_ref_checklist_group set title_en = 'Incompatible goals' where group_no = 7;
update public.tripod_ref_checklist_group set title_en = 'Information and communication' where group_no = 8;
update public.tripod_ref_checklist_group set title_en = 'Accountability and organization' where group_no = 9;
update public.tripod_ref_checklist_group set title_en = 'Maintenance management' where group_no = 10;
update public.tripod_ref_checklist_group set title_en = 'Emergency preparedness and response' where group_no = 11;

update public.tripod_ref_precondition set text_en = 'Tools or equipment are not used in line with their intended characteristics (deviation from the correct original method, absence of standards, contrary to accepted logic, or other commonly accepted conventions — e.g. the colour red means safety).' where code = '1.A';
update public.tripod_ref_precondition set text_en = 'Working with the tool or equipment is difficult (how to use it is unclear, incorrect settings are hard to correct, likely problems are not clearly indicated, the required performance does not match the design).' where code = '1.B';
update public.tripod_ref_precondition set text_en = 'The tool or equipment does not match people''s physical capabilities (strength, height, eyesight, reach).' where code = '1.C';
update public.tripod_ref_precondition set text_en = 'The tool or equipment does not match staff understanding, performance or mental capacity (too complex, too vague, confusing).' where code = '1.D';
update public.tripod_ref_precondition set text_en = 'The tool or equipment does not give an adequate view of the operation or process in progress (no measuring instruments, computer process control is not transparent, blind spots exist).' where code = '1.E';
update public.tripod_ref_precondition set text_en = 'After a change of state, execution of a work instruction or the start of an operation or process, the tool or equipment cannot provide proper feedback (e.g. “the valve is open” while the indicator shows the operation as running).' where code = '1.F';
update public.tripod_ref_precondition set text_en = 'The work environment has not been made adequately safe (interference between tools or equipment, cluttered layout, hazardous positions).' where code = '1.G';
update public.tripod_ref_precondition set text_en = 'Because of the design method, maintaining a tool or part of the equipment is difficult (parts do not arrive or arrive with difficulty, the whole system has to be dismantled).' where code = '10.A';
update public.tripod_ref_precondition set text_en = 'Maintenance of tools or equipment is temporary (non-standard materials and workmanship).' where code = '10.B';
update public.tripod_ref_precondition set text_en = 'Tools or equipment are not available.' where code = '10.C';
update public.tripod_ref_precondition set text_en = 'Detection, alarm and blowdown equipment is not reliable (in terms of initial setting and calibration).' where code = '10.D';
update public.tripod_ref_precondition set text_en = 'Inadequate use of safety and protective equipment (safety barriers are not in place; PPE exists but is not used).' where code = '11.A';
update public.tripod_ref_precondition set text_en = 'Safety and protective equipment is not available (no PPE available, equipment insufficient for hazardous situations).' where code = '11.B';
update public.tripod_ref_precondition set text_en = 'The detection and warning system does not signal danger properly (it does not work, gives insufficient time, is not easily seen or heard, is impossible to understand, or has become too routine).' where code = '11.C';
update public.tripod_ref_precondition set text_en = 'There is no suitable procedure for controlling the operation during emergencies and disturbances (its objectives and capability are limited).' where code = '11.D';
update public.tripod_ref_precondition set text_en = 'The operational systems for emergencies do not have the necessary effectiveness and do not cover the operations.' where code = '11.E';
update public.tripod_ref_precondition set text_en = 'Rescue facilities and services are below the required capacity or capability (medical services, building evacuation, firefighting systems and standby equipment are not managed).' where code = '11.F';
update public.tripod_ref_precondition set text_en = 'Tools or equipment no longer perform adequately and are not in optimum condition (fully or partly) — excessive corrosion, wear, less than 100% reliability.' where code = '2.A';
update public.tripod_ref_precondition set text_en = 'Maintenance of the tool or equipment relies on temporary fixes (non-standard materials or parts, or maintenance carried out by unskilled people).' where code = '2.B';
update public.tripod_ref_precondition set text_en = 'Access to the tool or equipment is inadequate (not purchased, not in stock, previously used, obtained late or incorrectly, unusable because it is under repair).' where code = '2.C';
update public.tripod_ref_precondition set text_en = 'The tool or equipment is not compatible with the intended work (does not match the objectives, expired, poor brand, poor quality, wrong characteristics).' where code = '2.D';
update public.tripod_ref_precondition set text_en = 'The procedure does not exist or is not properly available (it does not exist, cannot be found, or is hard to access).' where code = '3.A';
update public.tripod_ref_precondition set text_en = 'The procedure is incomplete (incorrect, out of date, contradictory, unsuitable; the formal procedure does not match usual working practice).' where code = '3.B';
update public.tripod_ref_precondition set text_en = 'The procedure is not comprehensible (in a foreign language, hard to work with because of poor interpretation, illogically arranged, complicated description).' where code = '3.C';
update public.tripod_ref_precondition set text_en = 'The procedure does not help much in carrying out the task fully (too little information, unclear warnings, no reference to the actions needed when a fault occurs).' where code = '3.D';
update public.tripod_ref_precondition set text_en = 'Several procedures exist (there is no effective system for selecting and enforcing the most effective procedure).' where code = '3.E';
update public.tripod_ref_precondition set text_en = 'Undefined and unfamiliar words and terms in the procedure discourage users from using it.' where code = '3.F';
update public.tripod_ref_precondition set text_en = 'External or environmental conditions affect or disrupt the operation (noise, bad smell, vibration, high temperature, wind, direct radiation, rain, atmospheric disturbances, humidity, darkness, dust, cloud, chemicals, a hostile environment).' where code = '4.A';
update public.tripod_ref_precondition set text_en = 'Personal factors or behavioural and work patterns disrupt the operation or the level of alertness (illness, misuse of medication, long working hours, disruption of the day–night rhythm, night shift, post-lunch nap, Ramadan).' where code = '4.B';
update public.tripod_ref_precondition set text_en = 'Use of drugs, alcohol or other substances that affect human behaviour (impaired perception of the surroundings, errors in assessment and problem-solving, inability to think clearly).' where code = '4.C';
update public.tripod_ref_precondition set text_en = 'Reduced attention to the task at hand (inattention, problems at home, problems with colleagues or the boss at work, poor attitude and conduct, monotonous work).' where code = '4.D';
update public.tripod_ref_precondition set text_en = 'Excessive attention to the task at hand (over-focus, a “you can do it” behavioural culture, excessive ambition, over-confidence in one''s own ability, inability to delegate, fear of failure, unusual stubbornness, bullying behaviour).' where code = '4.E';
update public.tripod_ref_precondition set text_en = 'The facilities, tools, equipment or ground surface of the work environment are dirty (slippery surface, measuring instruments not legible, no quick access to materials).' where code = '5.A';
update public.tripod_ref_precondition set text_en = 'The work environment is not properly tidy (obstacles present, little working space, inability to work with high efficiency).' where code = '5.B';
update public.tripod_ref_precondition set text_en = 'The arrangement and organization of the equipment is inadequate (inability to find the needed materials, inability to work with high efficiency).' where code = '5.C';
update public.tripod_ref_precondition set text_en = 'Personnel do not have adequate knowledge or sufficient insight into the type of work and how to perform their task (insufficient experience, their training was not effective).' where code = '6.A';
update public.tripod_ref_precondition set text_en = 'Personnel do not have adequate experience of performing their task (they have had no on-the-job training).' where code = '6.B';
update public.tripod_ref_precondition set text_en = 'Personnel do not have adequate ability to perform their tasks.' where code = '6.C';
update public.tripod_ref_precondition set text_en = 'Speed in carrying out the operation leads to careless work and to parts of the procedures being ignored.' where code = '7.A';
update public.tripod_ref_precondition set text_en = 'Production is increased without regard to the conditions (no continuous maintenance plan, poor work organization, an over-long working period).' where code = '7.B';
update public.tripod_ref_precondition set text_en = 'A potentially hazardous situation has been overlooked (corrective action has been postponed in order to keep production going).' where code = '7.C';
update public.tripod_ref_precondition set text_en = 'Activity continues even though personnel are aware that the working conditions are unsafe (actions or maintenance actions have been temporarily suspended by a competent HSE authority).' where code = '7.D';
update public.tripod_ref_precondition set text_en = 'Personnel work under pressure (because of production targets, the social environment, or the orders of a senior).' where code = '7.E';
update public.tripod_ref_precondition set text_en = 'Important information has not been properly sent or forwarded to the relevant staff, units and departments (weak transmission from the source, or weak communication channels).' where code = '8.A';
update public.tripod_ref_precondition set text_en = 'Important information is not requested by the relevant staff, units or departments.' where code = '8.B';
update public.tripod_ref_precondition set text_en = 'Important information is sent but is not properly received by the relevant staff, units or departments, or is received with a long delay (the information is transmitted but is not properly received and delivered).' where code = '8.C';
update public.tripod_ref_precondition set text_en = 'Important messages are misinterpreted or misunderstood (received but not understood, unclear, hard to understand, or open to interpretation).' where code = '8.D';
update public.tripod_ref_precondition set text_en = 'The recipient does not respond adequately to the message (it is understood but no action is taken; it is habitually set aside).' where code = '8.E';
update public.tripod_ref_precondition set text_en = 'Inadequate supervision (supervisors absent or overloaded, work permits completed poorly, hazardous combinations of activities not identified by the supervisors).' where code = '9.A';
update public.tripod_ref_precondition set text_en = 'There is no full understanding of all the activities within the company (activities and situations are not monitored).' where code = '9.B';
update public.tripod_ref_precondition set text_en = 'Poorly performing personnel are not dealt with or replaced (with no performance assessment or follow-up).' where code = '9.C';
update public.tripod_ref_precondition set text_en = 'Incorrect or irresponsible decisions are made (on the wrong grounds, in too short a time, without authorization, by an unrelated person).' where code = '9.D';
update public.tripod_ref_precondition set text_en = 'Planning of the activities is inadequate (errors in estimation and coordination, causing delays or several processes coinciding).' where code = '9.E';
update public.tripod_ref_precondition set text_en = 'The means for the tasks that have to be performed are inadequate (poor allocation of the capital, materials, time and people relevant to the job).' where code = '9.F';
update public.tripod_ref_precondition set text_en = 'The prevailing culture in the company is unhealthy (personnel do not work safely and have no genuine interest in the work).' where code = '9.G';

update public.tripod_ref_hidden_failure set text_en = 'The design is not suitable for the environmental conditions of the operation (temperature, humidity, heavy dust).' where code = '1.01';
update public.tripod_ref_hidden_failure set text_en = 'The design does not conform to industrial standards (wrong standard guideline, out of date, criteria not taken into account).' where code = '1.02';
update public.tripod_ref_hidden_failure set text_en = 'Process criteria were not fully taken into account during design (missing operating characteristics, incorrect and inadequate or out-of-date requirements).' where code = '1.03';
update public.tripod_ref_hidden_failure set text_en = 'Ergonomic considerations were not adequately taken into account during design (no ergonomic assessment, the designer was not familiar with the operating environment).' where code = '1.04';
update public.tripod_ref_hidden_failure set text_en = 'Poor communication between the designer and the user during the design, modification or hand-over stage.' where code = '1.05';
update public.tripod_ref_hidden_failure set text_en = 'Financial constraints or time pressure during design or modification (modifications or decommissioning are costly, parts of the design were dropped during the design stage).' where code = '1.06';
update public.tripod_ref_hidden_failure set text_en = 'New or modified designs are not introduced (lack of information, poor implementation of designs, not enough time allocated to implement designs).' where code = '1.07';
update public.tripod_ref_hidden_failure set text_en = 'Inadequate control of the design process (control of design change, inspection against standards/guidelines, quality control).' where code = '1.08';
update public.tripod_ref_hidden_failure set text_en = 'The design philosophy is inappropriate (no effective ergonomic design used, failure to use experience or industry-relevant information).' where code = '1.09';
update public.tripod_ref_hidden_failure set text_en = 'No control over the procurement of construction materials (materials purchased differ from previous ones, materials do not match the design characteristics).' where code = '1.10';
update public.tripod_ref_hidden_failure set text_en = 'Because of the design method, maintaining a tool or part of the equipment is difficult (parts do not arrive or arrive with difficulty, the whole system has to be opened up).' where code = '10.01';
update public.tripod_ref_hidden_failure set text_en = 'The records or documentation on the “setting” of a tool or equipment are inadequate (repeated mistakes, the device setting keeps being moved back and forth).' where code = '10.011';
update public.tripod_ref_hidden_failure set text_en = 'The tools or equipment used for maintenance are difficult to use (poor ergonomic design).' where code = '10.02';
update public.tripod_ref_hidden_failure set text_en = 'The materials, tools or equipment needed for maintenance are not of adequate quality.' where code = '10.03';
update public.tripod_ref_hidden_failure set text_en = 'The work instructions for maintenance tasks are inadequate (not up to date, not effective, not correct).' where code = '10.04';
update public.tripod_ref_hidden_failure set text_en = 'The maintenance documentation is inadequate (no guideline, or a non-standard guideline, or an unauthorized draft).' where code = '10.05';
update public.tripod_ref_hidden_failure set text_en = 'Human factors have a harmful effect on maintenance performance (problems at work and at home, illness, use of medication, addiction, or disruption of the day–night rhythm).' where code = '10.06';
update public.tripod_ref_hidden_failure set text_en = 'Environmental conditions disrupt maintenance work (very high temperature, darkness, noise, bad smell, wind and rain).' where code = '10.07';
update public.tripod_ref_hidden_failure set text_en = 'The experience and knowledge of the maintenance personnel is inadequate (no specific on-the-job training).' where code = '10.08';
update public.tripod_ref_hidden_failure set text_en = 'Resource constraints make proper maintenance difficult (very few maintenance staff, low purchasing budget, very short time).' where code = '10.09';
update public.tripod_ref_hidden_failure set text_en = 'There is not enough cooperation between the inspection team and maintenance (defective materials or equipment not reported).' where code = '10.10';
update public.tripod_ref_hidden_failure set text_en = 'Planning and coordination of maintenance activities is inadequate (no comprehensive view of maintenance operations, no prioritization of critical items, no proper maintenance plan).' where code = '10.12';
update public.tripod_ref_hidden_failure set text_en = 'The work-permit system for maintenance operations is inadequate.' where code = '10.13';
update public.tripod_ref_hidden_failure set text_en = 'Quality control of maintenance is inadequate (no report on how effective it is, no practical testing or inspection).' where code = '10.14';
update public.tripod_ref_hidden_failure set text_en = 'The ergonomic design of the safety and emergency equipment or protective devices is inadequate (difficult to operate, the alarm signal is not properly received).' where code = '11.01';
update public.tripod_ref_hidden_failure set text_en = 'Maintenance of the safety and emergency equipment or protective devices is inadequate (fire-extinguishing units and firefighting clothing not checked, alarm systems (sirens) and emergency exits not tested).' where code = '11.02';
update public.tripod_ref_hidden_failure set text_en = 'Emergency rescue or evacuation planning is not effective (not up to date, not sufficiently informative or flexible — e.g. what to do in which situation is not clear).' where code = '11.03';
update public.tripod_ref_hidden_failure set text_en = 'The emergency instructions / crisis-condition operational planning are inadequate (not up to date, not sufficiently informative or flexible — what to do in which situation is not clear, the last line of defence is not defined).' where code = '11.04';
update public.tripod_ref_hidden_failure set text_en = 'Environmental conditions during emergency operations are unsuitable (weather conditions, darkness).' where code = '11.05';
update public.tripod_ref_hidden_failure set text_en = 'The condition of the people during emergency operations is inadequate (fear, illness and stress).' where code = '11.06';
update public.tripod_ref_hidden_failure set text_en = 'Congestion or chaos in the operational environment hinders protective actions or emergency operations (inability to find the needed equipment, blocked emergency exits or escape routes).' where code = '11.07';
update public.tripod_ref_hidden_failure set text_en = 'The personnel involved are not sufficiently familiar with how to carry out emergency operations or protective actions and are not aware of their own capabilities (inadequate operational knowledge and emergency training, no first-aid skills).' where code = '11.08';
update public.tripod_ref_hidden_failure set text_en = 'The exchange of information on safety aspects between different sites, different departments or company personnel is inadequate.' where code = '11.09';
update public.tripod_ref_hidden_failure set text_en = 'Communication during an emergency is not effective (inadequate communication structure, no access, communication cut off).' where code = '11.10';
update public.tripod_ref_hidden_failure set text_en = 'Incompatibility between production, financial, government or personal goals and safety measures prevents a proper response in an emergency (prolonged shutdown time, difficulty informing people outside the organization).' where code = '11.11';
update public.tripod_ref_hidden_failure set text_en = 'Financial and human investment is no guarantee that the protective measures, emergency instructions or safety equipment are effective (ineffective investment in solving the problem).' where code = '11.12';
update public.tripod_ref_hidden_failure set text_en = 'The organization is not sufficiently involved in safety (no systematic record of who works where, safety not embedded in the organization''s methods, no policy to motivate safety).' where code = '11.13';
update public.tripod_ref_hidden_failure set text_en = 'The organizational structure designed for emergencies and other safety-related activities is inadequate (in terms of hierarchy, accountability, delegation).' where code = '11.14';
update public.tripod_ref_hidden_failure set text_en = 'The system for supplying tools or equipment is inadequate (inventory, administration, orders, distribution).' where code = '2.01';
update public.tripod_ref_hidden_failure set text_en = 'The procedure for using tools or equipment is inadequate (leads to incorrect use).' where code = '2.02';
update public.tripod_ref_hidden_failure set text_en = 'The specifications and requirements for tools or equipment are inadequate (performance, quality, brand, material, size, etc.).' where code = '2.03';
update public.tripod_ref_hidden_failure set text_en = 'The system for periodically reviewing, assessing and updating tool or equipment specifications is inadequate.' where code = '2.04';
update public.tripod_ref_hidden_failure set text_en = 'Tools or equipment are used under unsuitable conditions (outside the intended design characteristics, e.g. using corrosion-prone materials in a humid environment).' where code = '2.05';
update public.tripod_ref_hidden_failure set text_en = 'Tools or equipment are not stored correctly or not thoroughly cleaned (parts lost, damaged or very dirty).' where code = '2.06';
update public.tripod_ref_hidden_failure set text_en = 'Tools or equipment are used incorrectly (by an untrained, inexperienced or unqualified person).' where code = '2.07';
update public.tripod_ref_hidden_failure set text_en = 'Inadequate maintenance of tools or equipment (planning, execution, recording).' where code = '2.08';
update public.tripod_ref_hidden_failure set text_en = 'Financial constraints or time pressure when purchasing or modifying tools or equipment (poor quality, wrong quantity, necessary modifications not carried out).' where code = '2.09';
update public.tripod_ref_hidden_failure set text_en = 'The tool or equipment inspection system is inadequate (inspection frequency insufficient, inspections not complete, inspection intervals not matched to the criticality of the equipment, tool or material).' where code = '2.10';
update public.tripod_ref_hidden_failure set text_en = 'Communication between the technical inspection unit and maintenance is inadequate (unusable materials not reported, or reported poorly).' where code = '2.11';
update public.tripod_ref_hidden_failure set text_en = 'Control of the tools or equipment used in the workplace is inadequate (theft).' where code = '2.12';
update public.tripod_ref_hidden_failure set text_en = 'The tool or equipment control system — both at purchase and afterwards — does not comply with the contractual characteristics and requirements.' where code = '2.13';
update public.tripod_ref_hidden_failure set text_en = 'Follow-up of equipment inspection reports is inadequate.' where code = '2.14';
update public.tripod_ref_hidden_failure set text_en = 'The procedure is not suitable for use (illegible from repeated use, torn or dirty).' where code = '3.01';
update public.tripod_ref_hidden_failure set text_en = 'The system for keeping and retrieving the procedure is inadequate (no index or a poor index, kept far from the workplace, a permit needed to use it).' where code = '3.02';
update public.tripod_ref_hidden_failure set text_en = 'The format of the procedure is inadequate (no revision date, no table of contents, no author details).' where code = '3.03';
update public.tripod_ref_hidden_failure set text_en = 'Staff are not disciplined in using the procedure (the procedure is not returned, or is lost or dirtied).' where code = '3.04';
update public.tripod_ref_hidden_failure set text_en = 'The procedure is drafted by unsuitable people (no specific operational knowledge, no knowledge or experience of the initial draft).' where code = '3.05';
update public.tripod_ref_hidden_failure set text_en = 'There are constraints on improving, revising or correcting the procedure (lack of budget, too little time, too few staff).' where code = '3.06';
update public.tripod_ref_hidden_failure set text_en = 'There is no proper feedback on the practical use of the procedure (on corrections, completeness, effectiveness, usefulness).' where code = '3.07';
update public.tripod_ref_hidden_failure set text_en = 'There is no proper format for commenting on or approving the procedure (valid remarks and viewpoints on procedure revision are not applied).' where code = '3.08';
update public.tripod_ref_hidden_failure set text_en = 'The distribution list for the procedure is not defined.' where code = '3.09';
update public.tripod_ref_hidden_failure set text_en = 'The procedure was written for non-operational purposes (e.g. to demonstrate competence, for insurance purposes, to obtain ISO).' where code = '3.10';
update public.tripod_ref_hidden_failure set text_en = 'Supervision of procedure implementation is inadequate (the timing of supervision is wrong, no check that staff correctly understand the introduced procedure).' where code = '3.11';
update public.tripod_ref_hidden_failure set text_en = 'Control of the quality and quantity of the procedures in the organization is inadequate (no person responsible for keeping and improving the procedure, no review of the whole set of procedures, no quality control of contractors'' procedures).' where code = '3.12';
update public.tripod_ref_hidden_failure set text_en = 'The organization pays no attention to safety issues during changes and improvements (safety is not built into working methods, there is no policy that encourages safe working).' where code = '3.13';
update public.tripod_ref_hidden_failure set text_en = 'Unsound design or lack of insulation of equipment that generates noise, vibration or high temperature.' where code = '4.01';
update public.tripod_ref_hidden_failure set text_en = 'There is no proper personal protection against harmful external effects (no sunshade, ventilation, ear protection, heat-insulating clothing).' where code = '4.02';
update public.tripod_ref_hidden_failure set text_en = 'There is no suitable procedure that defines the environmental conditions under which work must be stopped (e.g. above 50°C or below −40°C).' where code = '4.03';
update public.tripod_ref_hidden_failure set text_en = 'Insufficient attention is paid to keeping the workplace clean and tidy (unpleasant smells).' where code = '4.04';
update public.tripod_ref_hidden_failure set text_en = 'Staff are not sufficiently acclimatized to the physical environment, weather or atmospheric conditions.' where code = '4.05';
update public.tripod_ref_hidden_failure set text_en = 'Physical conditions and their negative effects on staff are not reported to management.' where code = '4.06';
update public.tripod_ref_hidden_failure set text_en = 'There are not enough resources to improve the working environment (lack of budget, lack of time, too few staff).' where code = '4.07';
update public.tripod_ref_hidden_failure set text_en = 'Work decisions in this (adverse) environment are taken on the basis of financial or technical/production considerations.' where code = '4.08';
update public.tripod_ref_hidden_failure set text_en = 'There are no sound methods for identifying people with personal problems.' where code = '4.09';
update public.tripod_ref_hidden_failure set text_en = 'There are no sound methods for identifying people who are ill or who take medication that affects their work.' where code = '4.10';
update public.tripod_ref_hidden_failure set text_en = 'There are no sound methods for identifying people with social problems (depression, hopelessness, problems with colleagues).' where code = '4.11';
update public.tripod_ref_hidden_failure set text_en = 'People''s inappropriate work behaviour is not closely monitored or corrected (no training in handing work over to others, no attention to motivational factors and fear of failure, no method for dealing with a bullying culture).' where code = '4.12';
update public.tripod_ref_hidden_failure set text_en = 'There is no sound method for identifying and managing inadequate working conditions (management is not willing to listen).' where code = '4.13';
update public.tripod_ref_hidden_failure set text_en = 'Adverse and unavoidable working conditions are not correctly identified, are poorly assessed, or are not addressed with suitable actions to reduce their adverse effects (storms and lightning, tornadoes, sandstorms, political unrest).' where code = '4.14';
update public.tripod_ref_hidden_failure set text_en = 'The work environment (facilities, equipment and tools) is not cleaned, or is cleaned rarely (because of the nature of the work the workplace becomes dirty quickly).' where code = '5.01';
update public.tripod_ref_hidden_failure set text_en = 'Tools or equipment cannot be kept clean, or are hard to clean, because of their shape or nature.' where code = '5.02';
update public.tripod_ref_hidden_failure set text_en = 'Storage space is inadequate, or the working space is so small that it cannot be kept tidy and clean.' where code = '5.03';
update public.tripod_ref_hidden_failure set text_en = 'Collection or treatment of the waste produced by the equipment or facilities is not done properly (sewage, effluent-collection pipework, inadequate treatment).' where code = '5.04';
update public.tripod_ref_hidden_failure set text_en = 'Cleaning equipment or materials are not available or are of poor quality.' where code = '5.05';
update public.tripod_ref_hidden_failure set text_en = 'The method for cleaning and tidying the work environment is inadequate (the cleaning cycle is not defined).' where code = '5.06';
update public.tripod_ref_hidden_failure set text_en = 'Weather conditions make proper cleaning and tidying difficult.' where code = '5.07';
update public.tripod_ref_hidden_failure set text_en = 'There are not enough resources to keep the ground surface of the workplace clean and tidy (low purchasing budget, short time, too few staff).' where code = '5.08';
update public.tripod_ref_hidden_failure set text_en = 'The training or experience of the staff for cleaning is inadequate.' where code = '5.09';
update public.tripod_ref_hidden_failure set text_en = 'Lack of awareness and poor communication about cleaning the work environment and equipment.' where code = '5.10';
update public.tripod_ref_hidden_failure set text_en = 'Poor and untimely reporting of inadequate cleaning quality in the environment.' where code = '5.11';
update public.tripod_ref_hidden_failure set text_en = 'Staff have no sense of belonging to the workplace (no motivation regarding the state of the environment — “that is the next shift''s task”).' where code = '5.12';
update public.tripod_ref_hidden_failure set text_en = 'Planning and definition of the scope of tasks and positions is not adequate or clear (which department or shift is responsible for cleaning which area? task lists and reviews).' where code = '5.13';
update public.tripod_ref_hidden_failure set text_en = 'There is not enough supervision of cleaning and tidying the work environment (inspections are not carried out).' where code = '5.14';
update public.tripod_ref_hidden_failure set text_en = 'The recruitment process for personnel was not carried out correctly (no proper medical examinations and assessment of people''s abilities).' where code = '6.01';
update public.tripod_ref_hidden_failure set text_en = 'The test of the effectiveness of the training provided was inadequate (no final test on the training content or the relevant skills).' where code = '6.02';
update public.tripod_ref_hidden_failure set text_en = 'Personnel were recruited on the basis of special considerations (financial considerations, discriminatory policies, regional programmes).' where code = '6.03';
update public.tripod_ref_hidden_failure set text_en = 'There are not enough resources to run the training programmes (funds, time).' where code = '6.04';
update public.tripod_ref_hidden_failure set text_en = 'No report is sent to the training manager/management on the quality and effectiveness of the training programmes.' where code = '6.05';
update public.tripod_ref_hidden_failure set text_en = 'The need for supplementary training programmes for trained personnel is not identified.' where code = '6.06';
update public.tripod_ref_hidden_failure set text_en = 'There is no standard for training programmes and no defined requirements for the competence needed to hold jobs.' where code = '6.07';
update public.tripod_ref_hidden_failure set text_en = 'The scheduling, coordination or planning of periodic training is inadequate (personnel not registered in time to attend training courses and obtain valid certificates).' where code = '6.08';
update public.tripod_ref_hidden_failure set text_en = 'Personnel do not have a training and career-development file.' where code = '6.09';
update public.tripod_ref_hidden_failure set text_en = 'There is no suitable guideline for the minimum training and experience required for a particular job.' where code = '6.10';
update public.tripod_ref_hidden_failure set text_en = 'There is no suitable guideline for establishing training requirements and training courses.' where code = '6.11';
update public.tripod_ref_hidden_failure set text_en = 'The quality of training and training programmes does not meet the standard and is not controlled (inadequate training, no standard).' where code = '6.12';
update public.tripod_ref_hidden_failure set text_en = 'Management and organization of training is weak (no owner, no control, no review).' where code = '6.13';
update public.tripod_ref_hidden_failure set text_en = 'No training course is approved or organized (management pays no attention to the issue of competence).' where code = '6.14';
update public.tripod_ref_hidden_failure set text_en = 'Personnel do not have the authority needed to stop activities (management has not clearly stated the importance of safety).' where code = '7.01';
update public.tripod_ref_hidden_failure set text_en = 'No proper report on potentially hazardous situations is given to the person who has the necessary authority.' where code = '7.02';
update public.tripod_ref_hidden_failure set text_en = 'Personality factors make prioritization difficult (shyness, excessive motivation, addiction; personal goals interfere with the work).' where code = '7.04';
update public.tripod_ref_hidden_failure set text_en = 'A person''s external circumstances make prioritization difficult (family problems, other activities that take priority).' where code = '7.05';
update public.tripod_ref_hidden_failure set text_en = 'Supervision to establish safe working conditions is inadequate (personal priorities have not been prevented).' where code = '7.06';
update public.tripod_ref_hidden_failure set text_en = 'Management commitment to establishing safe working conditions is inadequate (acting for short-term profit, implementing emergency-meeting resolutions to meet production targets).' where code = '7.07';
update public.tripod_ref_hidden_failure set text_en = 'Management does not have adequate awareness of the different goals that exist (operational priorities are not sufficiently clear, safety requirements are not addressed through annual planning).' where code = '7.08';
update public.tripod_ref_hidden_failure set text_en = 'There is a problem with external pressure on the management (political pressure; national policies lead to required competence not being respected in the recruitment process).' where code = '7.09';
update public.tripod_ref_hidden_failure set text_en = 'Personnel are under pressure to follow the instructions of informal groups (the rules are not accepted by management).' where code = '7.3';
update public.tripod_ref_hidden_failure set text_en = 'The information method is inadequate (the operation is manual).' where code = '8.01';
update public.tripod_ref_hidden_failure set text_en = 'The quality and quantity of communication equipment is inadequate (communication points cut off, very low capacity, too few communication devices, too few communication channels).' where code = '8.02';
update public.tripod_ref_hidden_failure set text_en = 'The effect of harmful external factors disrupts communication (adverse weather, noise).' where code = '8.03';
update public.tripod_ref_hidden_failure set text_en = 'The procedure for communication structures is inadequate (who should receive or request information? who should announce information?).' where code = '8.04';
update public.tripod_ref_hidden_failure set text_en = 'There is no procedure explaining how information is to be transmitted or requested (using words, abbreviations or hand signals for certain tasks such as crane driving is unsuitable; the procedure requires repetition to be understood).' where code = '8.05';
update public.tripod_ref_hidden_failure set text_en = 'Human factors make communication more difficult (use of drugs and alcohol, deafness, stubbornness).' where code = '8.06';
update public.tripod_ref_hidden_failure set text_en = 'Insufficient training is given in communicating in the best way (glossary, standard and abbreviations, hand signals for crane drivers, a simple and clear agreed method, the meaning of instructions).' where code = '8.07';
update public.tripod_ref_hidden_failure set text_en = 'Training of supervisors and managers in how to share information and knowledge is inadequate (they do not know who needs to know what).' where code = '8.08';
update public.tripod_ref_hidden_failure set text_en = 'There are language problems (native language, different accent and dialect).' where code = '8.09';
update public.tripod_ref_hidden_failure set text_en = 'There is no proper report on the effect of the communication channels (the effect of the newsletter, safety meetings and other communication channels is not assessed).' where code = '8.10';
update public.tripod_ref_hidden_failure set text_en = 'Incompatible goals prevent the transmission and receipt of information (no willingness to hear and tolerate bad news, time pressure).' where code = '8.11';
update public.tripod_ref_hidden_failure set text_en = 'There are constraints on purchasing or modifying communication equipment or structure.' where code = '8.12';
update public.tripod_ref_hidden_failure set text_en = 'There is not enough control over the correct use of communication devices and the follow-up of communication procedures.' where code = '8.13';
update public.tripod_ref_hidden_failure set text_en = 'An inadequate communication structure prevents information from being obtained, arriving in time and being received by the relevant person (over-long communication channels).' where code = '8.14';
update public.tripod_ref_hidden_failure set text_en = 'Management priorities have been set incorrectly (mismanagement of the company, arbitrary pursuit of wrong policies).' where code = '9.01';
update public.tripod_ref_hidden_failure set text_en = 'Organizational goals are not properly defined (quality is not a goal, or the goal is not practical).' where code = '9.02';
update public.tripod_ref_hidden_failure set text_en = 'The company''s prevailing practice is not properly or adequately defined (company management has no direction, has strayed from the company''s main purpose, one branch of the company''s activities has been removed and the company is in confusion).' where code = '9.03';
update public.tripod_ref_hidden_failure set text_en = 'Job descriptions are not fully defined (the work activities required are not defined in the job description, training is limited to the usual definitions of the work).' where code = '9.04';
update public.tripod_ref_hidden_failure set text_en = 'The company''s organization chart or communication structure is not fully defined (intra-organizational communication between individuals and different parts of the organization is not clear or effective).' where code = '9.05';
update public.tripod_ref_hidden_failure set text_en = 'The company''s organization and its communication structure are not effective (excessive paperwork and strictness, low standards, lack of flexibility).' where code = '9.06';
update public.tripod_ref_hidden_failure set text_en = 'Accountability or responsibility is not correctly and effectively defined (it is not clear who or which organizational unit is responsible for what; responsibility and accountability are given to different people).' where code = '9.07';
update public.tripod_ref_hidden_failure set text_en = 'There are several organizational units that are changing in terms of structure and management.' where code = '9.08';
update public.tripod_ref_hidden_failure set text_en = 'The internal control systems of the company are inadequate in terms of structure, resources and method (supervision spread too widely, execution and control in the hands of one person, inadequate supervision).' where code = '9.09';
update public.tripod_ref_hidden_failure set text_en = 'Organizational bodies outside the organization exert influence on the organization (government, external bodies).' where code = '9.10';

update public.tripod_ref_target_category set title_en = 'People', potential_damage_en = 'Injury or harm to the health of personnel or third parties' where code = 'people';
update public.tripod_ref_target_category set title_en = 'Equipment / capital', potential_damage_en = 'Damage to the unit or equipment, loss of materials, interruption or shutdown of operations, damage to third-party assets' where code = 'equipment_capital';
update public.tripod_ref_target_category set title_en = 'Environment', potential_damage_en = 'Damage to and pollution of the environment' where code = 'environment';
update public.tripod_ref_target_category set title_en = 'Reputation', potential_damage_en = 'Mass-media controversy, public attention, protest, prosecution, trade restrictions, regulatory action' where code = 'reputation';

