-- حذفِ جدولِ کاملاً مردهٔ system_dashboard_config
-- =============================================================================
-- کشف‌شده در ممیزیِ فنیِ ۱۶ شهریور ۱۴۰۵ (بخشِ SuperAdmin): فیچرِ «کارت‌هایِ
-- KPI داشبورد» طبقِ کامنتِ موجود در SuperAdminPanel.jsx («طبق خواسته‌ی
-- صریح حذف شد») عمداً از UI حذف شده بود، ولی جدولِ system_dashboard_config
-- و توابعِ loadDashboardConfig/saveDashboardConfig (در systemConfigApi.js)
-- هرگز پاک نشده بودند. grep در کل src/ و supabase/functions/ تأیید کرد
-- هیچ کدی (نه فرانت‌اند، نه هیچ Edge Function) دیگر به این جدول یا این دو
-- تابع ارجاع نمی‌دهد — توابعِ متناظر هم در همین دسته از تغییرات حذف شدند.
--
-- بدونِ ریسک برایِ بکاپ‌گیریِ شرکت‌ها: این جدول از قبل هم در فهرستِ
-- «جداولِ پیکربندیِ سراسری» بود که عمداً از بکاپِ هر شرکت بیرون گذاشته
-- می‌شود (ر.ک. supabase/functions/_shared/companyBackup.ts)، پس هیچ
-- مکانیزمِ Restore ای هم به وجودش وابسته نیست.
drop table if exists public.system_dashboard_config;
